### ISSUE TITLE
Please provide an example with Intel Movidius

### ISSUE THREAD

**Issue by 1605200517** [ufoym/deepo#10]
Movidius is an neurochip device on an USB stick. Note: I am not an associate of Intel.
An example for gender detection (not my blog) https://jokersys.com/2017/08/05/first-look-movidius-neural-compute-stick/

**Comment by ufoym** [comment]
Hi, @1605200517 . This issue seems to be neither bug report nor related feature request. Feel free to reopen if I have misunderstood. Thanks.
