### ISSUE TITLE
"nvidia-docker run -it ufoym/deepo bash" some issues occurred.

### ISSUE THREAD

**Issue by LN-Curiosity** [ufoym/deepo#103]
I successsfully install docker(18.09.5) and nvidia-docker.And then the docker could running normally.But when i exec "nvidia-docker run -it ufoym/deepo bash"command,some issues occurred.

**$ nvidia-docker run -it ufoym/deepo bash**
**output:**

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting 
container process caused "process_linux.go:424: container init caused \"process_linux.go:407: 
running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec 
command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=410,driver<411 --pid=3870 /home/chengyu/docker/overlay2/54f44a88f390b684ce13eae177fdd437e556a3aa2976104d286f2671b1ffe869/merged]\\\\nnvidia-container-cli: initialization error: cuda error: forward compatibility was attempted on non supported hw\\\\n\\\"\"": unknown.

**$ docker info**
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-119-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 56
Total Memory: 251.8GiB
Name: iot250
ID: 26PQ:AICI:LWUK:JMMA:3BKE:KCBP:SSU3:L3TB:BMUO:A42J:YZKY:6BPX
Docker Root Dir: /home/chengyu/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

**Comment by LN-Curiosity** [comment]
@ufoym excuse me,may i get some help from you?

**Comment by ufoym** [comment]
See https://github.com/NVIDIA/libnvidia-container/issues/3.
Hope this could be of some help.

**Comment by LN-Curiosity** [comment]
l am sorry to reply to you late.Now i worked it out.The reason why nvidia-docker reported such  error info is that my cude-10.0 isn't compatible with nvidia-driver.After updating my driver,my nvidia docker could run well by using deepo image.Thx for your help.@ufoym

**Comment by LN-Curiosity** [comment]
have solved the problem.
