### ISSUE TITLE
cannot import name '_update_worker_pids'

### ISSUE THREAD

**Issue by Kangsan-Jeon** [ufoym/deepo#104]
I use your docker image(ufoym/deepo:all-jupyter) for my project.
When I test RCAN model, I receive the error message.
The message is like 
---> 10 from torch._C import _set_worker_signal_handlers, _update_worker_pids, \
     11     _remove_worker_pids, _error_if_any_worker_fails
     12 from torch.utils.data.dataloader import DataLoader

ImportError: cannot import name '_update_worker_pids'

So, I test with pytorch/pytorch docker image.
The error doesn't show again.

Is it caused by pytorch version?
If so, how can I  solve the problem?

**Comment by ufoym** [comment]
See [here](https://github.com/CSAILVision/semantic-segmentation-pytorch/issues/157#issuecomment-477029931).

**Comment by Kangsan-Jeon** [comment]
Than for your reply.
But, I don't know how to download Pytorch v1.0.0 from your image.
I just use your image by "docker pull ufoym/deepo:all-jupyter".
So, if I want to download the lower version of pytorch, what can I do?

**Comment by ufoym** [comment]
We only provide prebuilt images with the latest PyTorch. You can, of course, try
```bash
python generator/generate.py Dockerfile pytorch --cuda-ver 10.0 --cudnn-ver 7
```
to build your own.

**Comment by Kangsan-Jeon** [comment]
I really appreciate your help.
