### ISSUE TITLE
Please consider supportting JupyterLab

### ISSUE THREAD

**Issue by Bingmang** [ufoym/deepo#109]
Thank you, your image is awesome and super useful, and the jupyterlab is very useful too!

**Comment by ufoym** [comment]
We've added JupyterLab by merging #58.
However, it is not contained in `deepo` pre-built images. You can generate your own `Dockerfile` by
```bash
python generator/generate.py docker/Dockerfile.all-jupyterlab tensorflow sonnet mxnet cntk keras pytorch chainer theano lasagne caffe torch darknet onnx jupyter jupyterlab
```

**Comment by Bingmang** [comment]
Thank you very much!
