### ISSUE TITLE
Add Kaldi support

### ISSUE THREAD

**Issue by synergiator** [ufoym/deepo#11]
Another one popular framework, specialized for ASR (audio speech recognition) is Kaldi

https://github.com/kaldi-asr/kaldi

**Comment by ufoym** [comment]
Can anyone provide a set of common deep-learning-based toolkits for speech recognition and add scripts for building images like `deepo:all-speech-py36-cu90`?

https://github.com/ufoym/deepo/blob/bc3705934c74ecfc3c901bba8b7af1b92fcdeea3/scripts/make-gen-docker.py#L68-L72

Related PRs are welcome.
