### ISSUE TITLE
unknown blob !! Does anybody face this problem?

### ISSUE THREAD

**Issue by Yangchunfighting** [ufoym/deepo#110]
[yangc@deepnex01 ~]$ sudo docker pull hub-mirror.c.163.com/ufoym/deepo
Using default tag: latest
latest: Pulling from ufoym/deepo
898c46f3b1a1: Pull complete 
63366dfa0a50: Downloading 
041d4cd74a92: Download complete 
6e1bee0f8701: Downloading 
112097260ef3: Download complete 
30a67c795176: Download complete 
0d286a7b6e12: Download complete 
5d089cae17f6: Download complete 
55dd29113cda: Download complete 
987b8ae28a17: Download complete 
0395fffb1efc: Download complete 
unknown blob

**Comment by ufoym** [comment]
It is probably not a deepo-related issue.
See https://stackoverflow.com/questions/48599288/docker-error-unknown-blob.
If the problem persists, please try another mirror.
