### ISSUE TITLE
PyTorch compiled with cuda and cudnn, so we don't need to build docker based on nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04.

### ISSUE THREAD

**Issue by ypw-rich** [ufoym/deepo#113]
PyTorch compiled with cuda and cudnn, so we don't need to build docker based on nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04.

cuda:10.0-base-ubuntu18.04 is only 115MB，but cuda:10.0-cudnn7-devel-ubuntu18.04 is 3.05GB.

**Comment by ufoym** [comment]
`cuda:10.0-base-ubuntu18.0` contains only the bare minimum (libcudart), while most DL frameworks depends on more CUDA packages?

**Comment by ypw-rich** [comment]
Because PyTorch already compiled with cuda, it doesn't load cuda in the system, so we can add a if else to PyTorch to avoid overpacking.

**Comment by ufoym** [comment]
@ypw-rich Thanks for the suggestion. Could you fix this and make a pull request? We will merge the code and trigger a rebuild for the related images.
