### ISSUE TITLE
the version of tensorflow 

### ISSUE THREAD

**Issue by wzl789139** [ufoym/deepo#117]
The version of tensorflow  in this image is 2.0  but now most code of tf is wrote with 1.0 .and tf 2.0  can not compatible with tf 1.0  code  easily.That make me can't  use this image

**Comment by ufoym** [comment]
Sorry for the inconvenience. 
Sadly we don't have enough resources to consider different versions for each module.
So we choose to build the images with the latest tools.
Anyway, you can build your own image with other versions.
