### ISSUE TITLE
Is there any images support ubuntu16.04?

### ISSUE THREAD

**Issue by wyjforwjy** [ufoym/deepo#119]
I find that the images pulled are from ubuntu18.04. So how can i get the earlier images? hope for your help.

**Comment by wyjforwjy** [comment]
@ufoym

I try create a new docker by dockfile,but it always occurs the "download time out error"...

**Comment by ufoym** [comment]
Try pulling images with deprecated tags like 
```
docker pull ufoym/deepo:py36-cu90
```

If you want to build your own images, try to specify `--ubuntu-ver` https://github.com/ufoym/deepo/blob/f15f97e097926f1df0d503b63fba062337c65092/generator/generate.py#L25
