### ISSUE TITLE
Tensorflow 1.4 error 

### ISSUE THREAD

**Issue by moh3th1** [ufoym/deepo#12]
I am trying to upgrade to tensorflow 1.4 but i have this error 
``` 
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```
  
![image](https://user-images.githubusercontent.com/15180702/32543974-da53118e-c47f-11e7-9b81-3fb4b6bdf39f.png)

**Comment by tfriedel** [comment]
I made a fork using python 3.6 and tensorflow 1.4 here:
https://github.com/tfriedel/deepo
https://hub.docker.com/r/tfriedel/deepo/

Works for me, maybe worth a try?

**Comment by ufoym** [comment]
@tfriedel Thanks!
@moh3th1 TensorFlow 1.4 should work in our [latest pre-built images](https://hub.docker.com/r/ufoym/deepo). Though there may be some warnings when you run the official build of TensorFlow 1.4 for Python 3.6 (see https://github.com/tensorflow/tensorflow/issues/14182).

**Comment by bastiaan-sjardin** [comment]
So just to confirm: I can use tf 1.4 with py3.6 and just ignore the warnings with all functionalities in tact?
