### ISSUE TITLE
Building wheel for torchvision (setup.py): finished with status 'error'

### ISSUE THREAD

**Issue by oiotoxt** [ufoym/deepo#120]
`$ docker build -f Dockerfile.pytorch-py36-cpu .`

Collecting git+https://github.com/pytorch/vision.git
  Cloning https://github.com/pytorch/vision.git to /tmp/pip-req-build-8_0m83s6
  Running command git clone -q https://github.com/pytorch/vision.git /tmp/pip-req-build-8_0m83s6
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision==0.5.0a0+7c9bbf5) (1.17.1)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.6/dist-packages (from torchvision==0.5.0a0+7c9bbf5) (1.12.0)
Requirement already satisfied, skipping upgrade: torch in /usr/local/lib/python3.6/dist-packages (from torchvision==0.5.0a0+7c9bbf5) (1.2.0)
Collecting pillow>=4.1.1 (from torchvision==0.5.0a0+7c9bbf5)
  Downloading https://files.pythonhosted.org/packages/14/41/db6dec65ddbc176a59b89485e8cc136a433ed9c6397b6bfe2cd38412051e/Pillow-6.1.0-cp36-cp36m-manylinux1_x86_64.whl (2.1MB)
Building wheels for collected packages: torchvision
  Building wheel for torchvision (setup.py): started
  **Building wheel for torchvision (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8_0m83s6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8_0m83s6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yob68akv --python-tag cp36
       cwd: /tmp/pip-req-build-8_0m83s6/**
  Complete output (513 lines):
  Building wheel torchvision-0.5.0a0+7c9bbf5
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/torchvision
  copying torchvision/utils.py -> build/lib.linux-x86_64-3.6/torchvision
  copying torchvision/extension.py -> build/lib.linux-x86_64-3.6/torchvision
...

Thank you.

**Comment by ufoym** [comment]
Fixed. Feel free to reopen it if you still have issues with the latest images.
