### ISSUE TITLE
latest pre-built images and build your own customized image

### ISSUE THREAD

**Issue by xudh1991** [ufoym/deepo#121]
at Tensorflow 1.4 error #12:
ufoym: TensorFlow 1.4 should work in our latest pre-built images.
But when I enter the connection latest pre-built images，I didn't find out the images of the latest pre-built images, and i find the way to 'build your own customized image with Lego-like modules'.  Build customized image is the latest pre-built images??? 
i want to build my own customize image with tensorflow1. ,pytorch1.2.0, opencv2. i don't know how to change the version of tensorflow and pytorch.

**Comment by ufoym** [comment]
That is a `latest image` built ~2 years ago.
We no longer provide TensorFlow 1.x in our latest pre-built images currently.
Though you can try to build your own one:
`python generator/generate.py ../docker/Dockerfile.tensorflow-py36-cpu tensorflow=1.13.1 python==3.6`

Sorry for any inconvenience!
