### ISSUE TITLE
build "Dockerfile.pytorch-py36-cu100" failed

### ISSUE THREAD

**Issue by threeds** [ufoym/deepo#122]
I build Dockerfile.pytorch-py36-cu100 and get following erros:
 In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:9:0,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /usr/local/lib/python3.6/dist-packages/torch/include/torch/extension.h:4,
                     from /tmp/pip-req-build-qngbrekv/torchvision/csrc/cpu/vision_cpu.h:2,
                     from /tmp/pip-req-build-qngbrekv/torchvision/csrc/cpu/nms_cpu.cpp:1:
    /tmp/pip-req-build-qngbrekv/torchvision/csrc/cpu/nms_cpu.cpp: In lambda function:
    /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:150:56: warning: ‘c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)’ is deprecated [-Wdeprecated-declarations]
         at::ScalarType _st = ::detail::scalar_type(the_type);                    \
                                                            ^
    /tmp/pip-req-build-qngbrekv/torchvision/csrc/cpu/nms_cpu.cpp:77:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’
       AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms", [&] {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Dispatch.h:78:23: note: declared here
     inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties &t) {
                           ^~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-qngbrekv/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-qngbrekv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-atymsmb4/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by ufoym** [comment]
Fixed. Feel free to reopen it if you still have issues with the latest images.
