### ISSUE TITLE
Python dumped when trying to import tensorflow

### ISSUE THREAD

**Issue by Frankr0** [ufoym/deepo#123]
I am a beginner in docker, when I follow the quick start instruction:
`docker run --runtime=nvidia --rm ufoym/deepo nvidia-smi`
got:
```
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
```

Is ` --runtime=nvidia` deprecated?

As the instruction of the nvidia-docker I use `--gpus` instead of `--runtime=nvidia`:
`docker run --gpus all -it --ipc=host ufoym/deepo bash`  

But:
```
root@ea810a8cf7b7:/# python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)
root@ea810a8cf7b7:/# 
```

Was there anything wrong with what I did?  Thx

**Comment by ufoym** [comment]
Fixed. Feel free to reopen it if you still have issues with the latest images.
BTW, `--runtime=nvidia` is deprecated and should be replaced by `--gpus all`. Thank you for pointing out our mistake.
