### ISSUE TITLE
Which cudnn version do the images use exactly？

### ISSUE THREAD

**Issue by XIEYUNSCUT** [ufoym/deepo#124]
the web page just say the cudnn version is cudnnv7, but we know v7 may means many different versions,like v7.0.0 or v7.6.3 and so on,can you tell which version is used exactly?

**Comment by ufoym** [comment]
Take `all-jupyter-py36-cu101` for example, the images are built based on `nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04`. See https://github.com/ufoym/deepo/blob/377f82afe19324f29d3b538ee790b53d4cd42e2e/docker/Dockerfile.all-jupyter-py36-cu101#L22

Therefore the cuDNN version depends on the official images provided by NVidia, which are also kept updating. Currently, it is `7.6.4.38` (see https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu18.04/10.1/devel/cudnn7/Dockerfile#L5).
