### ISSUE TITLE
Because the latest NVIDIA docker does not support docker compose, is there currently no way to use Pycharm: Remote interpreter using Docker？？

### ISSUE THREAD

**Issue by opptimus** [ufoym/deepo#127]
I want to use Pycharm for GPU development and code debugging in Ubuntu 18.04 with docker,**Because the latest NVIDIA docker does not support docker compose**, is there currently no way to use Pycharm: Remote interpreter using Docker load GPU device?
 except for the method of connecting to Remote SSH.

**Comment by ufoym** [comment]
Sorry for any inconvenience. We have not tested the images in this way. 
Maybe the following links help:
- https://timodenk.com/blog/connecting-pycharm-to-a-tensorflow-docker-container
- https://www.jetbrains.com/help/pycharm/docker.html

**Comment by opptimus** [comment]
@ufoym Thanks
