### ISSUE TITLE
Running deepo on windows or ubuntu-in-virtualbox on a machine with Intel HD graphics

### ISSUE THREAD

**Issue by scirahul** [ufoym/deepo#13]
Hi there,
I am a newbie who wants to tryout deepo image. Is this supposed to be run only on machine with Nvidia GPUs? Is there some way I can make it run on windows 10 or ubuntu-in-virtualbox on a machine with Intel HD graphics.

Why is the deepo-image tightly coupled to nvidia-docker (instead of just docker)?

Thanks,
- Rahul

**Comment by ufoym** [comment]
@scirahul Yes, deepo is supposed to be run on a Linux system with CUDA-capable GPUs. Use `nvidia-docker` rather than `docker` as we have to run deepo leveraging NVIDIA GPUs.

**Comment by scirahul** [comment]
Thanks I understand nvidia-docker will perform better. But if I want to run deepo on a machine with Intel's onboard GPU, what changes need to be made.

I guess this feature support will enable and encourage more people to use deepo.

**Comment by ufoym** [comment]
@scirahul Deepo is now supporting **cpu-only** env. See https://github.com/ufoym/deepo#cpu-version
