### ISSUE TITLE
logging in python fails to write to STDOUT

### ISSUE THREAD

**Issue by Genius1237** [ufoym/deepo#130]
As of last week, using the `logging` library (with the default argument) to log statements in python would results in those statements appearing in STDOUT. As of today, this isn't happening, i.e all statements logged with `logging` are not appearing in STDOUT.

Has some change been made to images? I'm using `pytorch-py36` btw.

**Comment by Genius1237** [comment]
To add some info, previously using `logging.info` in a program would print the logged value to stdout, but it does not do so now.

**Comment by ufoym** [comment]
@Genius1237 Could you provide a minimal example for reproducing the problem?

**Comment by Genius1237** [comment]
I seem to have narrowed down the issue. It has something to do with the pytorch installation in the docker image.

Running the following code-snippet shows the error. Run it with and without the line that does `import torch`. When the line is there, the message logged via `logger.info` does not appear on stdout.
```
import logging
import torch

logger = logging.getLogger(__name__)

def main():
    logging.basicConfig(format="%(asctime)s - %(levelname)s - %(name)s -   %(message)s",
                        datefmt="%m/%d/%Y %H:%M:%S",
                        level=logging.INFO)
    logger.info("info")
    logger.warn("warn")

if __name__ == "__main__":
    main()
```

**Comment by ufoym** [comment]
Probably. The following code works.
```python
import logging
import torch
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.info('ok')
```
