### ISSUE TITLE
Add support to ppc64le

### ISSUE THREAD

**Issue by teelinsan** [ufoym/deepo#131]
Hi,
I'd appreciate the support of Power PC 64bit little endian architecture (ppc64le).
Ubuntu and Nvidia already have base images with this architecture: https://hub.docker.com/r/nvidia/cuda-ppc64le
I am available to contribute and test it.

**Comment by ufoym** [comment]
That's cool. Pull request welcome.

**Comment by teelinsan** [comment]
I'm working on it. Once I've something stable I'll do the pull request.
The main problem is that most of the libraries are not compiled for the ppc64le architecture, so I have to install them from sources...  I plan to support just the tags tensorflow and pytorch for the moment.
