### ISSUE TITLE
How can I use YOLOv3 on this image?

### ISSUE THREAD

**Issue by Jureong** [ufoym/deepo#135]
Hi. Thank you for providing a great image.
Actually I'm new to using Docker, and confused with making use of commands on Docker containers.
I'm gonna execute YOLOv3, darknet. 
You explained that "$ darknet <function>" on README, but I need more specific instruction about it.
I would appreciate if you answer me.

**Comment by ufoym** [comment]
Please refer to https://pjreddie.com/darknet/yolo/
It shows how to run yolov3:
```
./darknet detect cfg/yolov3.cfg yolov3.weights data/dog.jpg
```
We have `./darknet`. So all you need are `yolov3.cfg`, `yolov3.weights` and an input image.
