### ISSUE TITLE
Custom CPU version | MacOs 

### ISSUE THREAD

**Issue by SoufianeDataFan** [ufoym/deepo#140]
I am using the CPU version on MacOs but I don't want to import all the DL libraries (just want Keras and Pytroch only). 

I tried this command `docker pull ufoym/deepo:keras pytorch` I get an error message: 

```
macs-MBP-606:docker_machine macbook$ docker pull ufoym/deepo:keras pytorch
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```

I also tried to follow the instructions of this [customization section](https://github.com/ufoym/deepo#build-your-own-customized-image-with-lego-like-modules) but I got another error 

```
macs-MBP-606:docker_machine macbook$ docker build -t deepo/ .
invalid argument "deepo/" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```

any help on this, please?

**Comment by ufoym** [comment]
Those are invalid commands.

You can try the following steps.

#### Step 1. prepare generator

```bash
git clone https://github.com/ufoym/deepo.git
cd deepo/generator
```

#### Step 2. generate your customized Dockerfile

For example, if you like `pytorch` and `keras`, then
```bash
python generate.py Dockerfile pytorch keras
```

This should generate a Dockerfile that contains everything for building `pytorch` and `keras`. Note that the generator can handle automatic dependency processing and topologically sort the lists. So you don't need to worry about missing dependencies and the list order.

#### Step 3. build your Dockerfile

```bash
docker build -t my/deepo .
```

This may take several minutes as it compiles a few libraries from scratch.
