### ISSUE TITLE
Is it possible to switch from a cpu to gpu version?

### ISSUE THREAD

**Issue by weiyengs** [ufoym/deepo#142]
Hi there, I was thinking of a solution of running the deepo image in my local(a macOS without GPU) and later moving the image to another machine(a linux with GPU). Is it possible to build the CPU image in my local because it only supports CPU in mac, and then later "switch" to the GPU version at a later time?

Thanks

**Comment by ufoym** [comment]
We haven't tried that yet, but theoretically it should be possible to install tons of dependencies (like cuda, cudnn) and rebuild tools with cuda / cudnn. Though we don't recommend this way since it should be a nightmare.
