### ISSUE TITLE
How to upgrade cuda for the image?

### ISSUE THREAD

**Issue by chenwydj** [ufoym/deepo#143]
I started using deepo, and on top of that I installed more packages, and then commit and pushed to my own dockerhub as another version.

What is the best practice to upgrade the cuda version for the image?

Thank you very much!

**Comment by ufoym** [comment]
You can specify cuda version in the following line:
https://github.com/ufoym/deepo/blob/40045012059ffd298a08fdb5e9f95436e7015642/scripts/make-gen-docker.py#L82

If what you wanted is to upgrade the cuda version to `11.1`, the latest deepo images should meet your requirement :)
