### ISSUE TITLE
Does 'darknet version' support opencv for darknet video detection?

### ISSUE THREAD

**Issue by Jureong** [ufoym/deepo#144]
It's the same as the title.

I've tried to install opencv 3.4.0 on the container from deepo:darknet.
And got the error like this.

-- Configuring incomplete, errors occurred!
See also "/root/opencv/opencv-3.4.0/build/CMakeFiles/CMakeOutput.log".
See also "/root/opencv/opencv-3.4.0/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
opencv-3.4.0.sh: 53: opencv-3.4.0.sh: sudo: not found
opencv-3.4.0.sh: 54: opencv-3.4.0.sh: sudo: not found
opencv-3.4.0.sh: 55: opencv-3.4.0.sh: sudo: not found

Please reply this. Thanks.

**Comment by ufoym** [comment]
Currently not since OpenCV is an optional dependency for Darknet.
Please follow this [instructions](https://docs.opencv.org/master/d2/de6/tutorial_py_setup_in_ubuntu.html) to install OpenCV in deepo:darknet:

**Comment by Jureong** [comment]
> Currently not since OpenCV is an optional dependency for Darknet.
> Please follow this [instructions](https://docs.opencv.org/master/d2/de6/tutorial_py_setup_in_ubuntu.html) to install OpenCV in `deepo:darknet`.

Even on webcam detection mode?
Thanks for your reply.
I'll follow the link.
