### ISSUE TITLE
Problem with cudnn

### ISSUE THREAD

**Issue by nagi1999a** [ufoym/deepo#149]
I am using the image tag `all-py36-cu111` to create LSTM model with Keras. However, I find that it will cause the following error:

`Fail to find the dnn implementation.`

And cause the following error in the console:

`Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0`

From the base image `nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04`, I find that the cudnn version `8.0.5.39` is too old for the latest `tensorflow-gpu` package. Due to this, the base image maybe need to change to `11.2.2-cudnn8-devel-ubuntu18.04`?

**Comment by ufoym** [comment]
Fixed 38c9607b06f089a9d3eea0455c39382b91cae1bd
