### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by bowenroom** [ufoym/deepo#19]
When I use the command ' docker pull ufoym/deepo' and after the download for a few minute, it has the following tips: unauthorized: authentication required. Want to know how to fix it,thanks!!

**Comment by ufoym** [comment]
We are updating some of the frameworks to the latest version and rebuilding the docker images. Sorry for any inconvenience!

**Comment by bowenroom** [comment]
That's Ok,we all thanks for this docker image, thanks for your effort!
