### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by impredicative** [ufoym/deepo#2]
Why is it Python 3.5 that is used and not 3.6?

**Comment by ufoym** [comment]
Ubuntu 16.04 comes with Python 3.5 by default. You can replace it with a new version by simply modifying Dockerfile and rebuilding your customized image.

**Comment by impredicative** [comment]
It's trivial to install Python 3.6 binary on Ubuntu. Why does Ubuntu matter anyway? What if I was using any other distro? Why intentionally use an old version of Python? `dict` is supposed to be much faster in 3.6.

**Comment by ufoym** [comment]
OK. We will consider supporting multiple versions of Python.

**Comment by tfriedel** [comment]
I made a fork using python 3.6 and tensorflow 1.4:
https://github.com/tfriedel/deepo

**Comment by ufoym** [comment]
Deepo2 now supports Python 2.7 / 3.6. 
All pre-built python-related images use `Python 3.6` by default. 
If you are unhappy with `Python 3.6`, you can also specify other python versions:
```bash
docker pull ufoym/deepo:py27
```

```bash
docker pull ufoym/deepo:tensorflow-py27
```

See https://hub.docker.com/r/ufoym/deepo/tags/ for a complete list of all available tags.
