### ISSUE TITLE
nvidia-docker run -v with all-py36-jupyter image

### ISSUE THREAD

**Issue by svenchilton** [ufoym/deepo#21]
I'm running your all-py36 and all-py36-jupyter images on a remote, gpu-equipped machine.  When I add -v ~/path/to/my/data:/data to the suggested nvidia-docker command for running the all-py36 image, I can access the data directory within the container.  However, when I make the same addition to the suggested command for running the all-py36-jupyter image and then use the browser on my local machine to open the Jupyter Notebook at [SERVER ADDRESS]:[JUPYTER PORT], I don't see the data directory anywhere in the file menu.  Am I doing something wrong?

**Comment by ufoym** [comment]
By default, Jupyter Notebook only accepts connections from localhost (eg, from the same computer that its running on). The suggested command
```nvidia-docker run -it -p 8888:8888 ufoym/deepo:all-py36-jupyter jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/root'```
should fix this issue.

But it should be noted that the default working directory is `/root`. And it is not possible to navigate to the parent directory such as `/data` for security reasons:

> The kernel might not be python, nor on the same machine than the server, nor do you need a running kernel to use server API(s).
see https://github.com/ipython/ipython/issues/7751

You could start the notebook in `/` instead:
```nvidia-docker run -it -p 8888:8888 ufoym/deepo:all-py36-jupyter jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/'```
