### ISSUE TITLE
How can I get image with cuda 8.0 and cudnn v6.0

### ISSUE THREAD

**Issue by dfayzur** [ufoym/deepo#26]
This docker image is an excellent work. Thank you very much for the work. 

Can I get older image with cuda 8.0 and cudnn v6.0 ?

**Comment by ufoym** [comment]
Thank you for choosing deepo. Unfortunately, we don't keep any images with older version of cuda / cudnn as there are already tons of images to be maintained currently. Could you tell us why you need those images? Maybe we should rethink our strategy.

**Comment by ufoym** [comment]
@dfayzur You can try `nvidia-docker run -it ufoym/deepo:all-py35`
