### ISSUE TITLE
Request to add xgboost

### ISSUE THREAD

**Issue by rishabhbhardwaj** [ufoym/deepo#3]

**Comment by ysh329** [comment]
docker pull kaggle/python:latest

**Comment by Leakermeli** [comment]
wow, that is so useful, as for me

**Comment by ufoym** [comment]
Deepo only provides deep learning based framework. At this time, there are no concrete plans for adding other ml-framework like xgboost. You can either try to modify Dockerfile to add xgboost, or `pull kaggle/python:latest` as @ysh329 said.
