### ISSUE TITLE
Converting to a Singularity container

### ISSUE THREAD

**Issue by negrinho** [ufoym/deepo#30]
Thanks for your work! This looks great.

I was trying to convert the all-in-one to a Docker image, but I'm having issues with the cuda support. It converts OK (creates the image), but upon running it complains that it can't find cuda. 

See below for the command to convert. 
```sudo singularity build py27-gpu.img docker://ufoym/deepo:all-py27```

Any tips? It would be nice if this worked with Singularity as that is what is effectively used in HPC environments.

**Comment by ufoym** [comment]
We are not familiar with Singularity. Sorry for any inconvenience. We are not sure if this issue can be fixed by [creating portable GPU-enabled singularity images](http://gpucomputing.shef.ac.uk/education/creating_gpu_singularity/).

**Comment by negrinho** [comment]
Thanks for the help. I figured it out. It may be useful to check [this](http://singularity.lbl.gov/docs-exec#a-gpu-example). The `--nv` option is important for running the container. This works:
```
sudo singularity build py27-gpu.img docker://ufoym/deepo:all-py27
singularity shell --nv py27-gpu.img
```
