### ISSUE TITLE
[New Feature] Any plans to add ONNX?

### ISSUE THREAD

**Issue by daizeng1984** [ufoym/deepo#33]
Thanks for the great work! Love this repo. Would be even nicer if you could consider adding ONNX as well.

**Comment by NokiaDDT** [comment]
onnx +1, thanks.

**Comment by ufoym** [comment]
ONNX has been added in the following images now:
- `latest`
- `all`
- `all-py36`
- `py36-cu90`
- `all-py36-cu90`
- `all-py27-cu90`
- `all-py27`
- `py27-cu90`
- `all-py36-cpu`
- `all-cpu`
- `py36-cpu`
- `cpu`
- `all-py27-cpu`
- `py27-cpu`
- `all-jupyter-py36-cu90`
- `all-jupyter-py36`
- `all-jupyter`
- `all-py27-jupyter`
- `py27-jupyter`
- `all-py36-jupyter-cpu`
- `py36-jupyter-cpu`
- `all-py27-jupyter-cpu`
- `py27-jupyter-cpu`
