### ISSUE TITLE
Please consider integrating with https://github.com/FloopCZ/tensorflow_cc

### ISSUE THREAD

**Issue by jimlloyd** [ufoym/deepo#34]
`deepo` seems very useful. I like the broad scope of supporting a diverse range of DL tools. But I believe it is missing one particular piece that I require. That piece is to build the C++ API, and is provided by https://github.com/FloopCZ/tensorflow_cc. 

@FloopCZ

**Comment by ufoym** [comment]
FloopCZ/tensorflow_cc#83
@jimlloyd

We appreciate all contributions related to popular/useful deep learning frameworks, no matter whether it is a Python library or not:-)
