### ISSUE TITLE
CuDnn library version does not match

### ISSUE THREAD

**Issue by zheng-xing** [ufoym/deepo#36]
Hi there, thanks for this great project. 

I had an error running tensorflow with the GPU.
The error messages are like this:
`
E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7102 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:712] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
`
I can fix the issue by downloading an lower version of CuDnn and run the following command:
`$ dpkg -i libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb"`.

I just wonder can you fix this problem for the docker image? 
Thanks.

**Comment by ufoym** [comment]
We have just checked the latest docker images and the problem seems to be fixed now.
