### ISSUE TITLE
Can you tell me where is the caffe install folder?

### ISSUE THREAD

**Issue by supernihui** [ufoym/deepo#4]
Your docker image is amazing and I have tested all deeplearning tools like caffe,tensorflow etc can work. But I want to find the location of the build folder of caffe. 
Thanks.

**Comment by ufoym** [comment]
Thank you. 
If you just need to know where the executable is, you can run `which <executable>`. 
For instance:
```
$ which caffe
/usr/local/bin/caffe
```
Note that we remove sources after building from them.

**Comment by coderzuo** [comment]
Could you keep the sources? Because some caffe layer, such as depth-wise and GIoU loss, need to add by users. Thus, some times users have to rebuild it.

Thanks.
