### ISSUE TITLE
Tensorflow source build with latest cuda

### ISSUE THREAD

**Issue by achalshah20** [ufoym/deepo#40]
Hi, I have a docker file which builds tensorflow from sources with latest cuda 9.2 and cudnn 7.1.4. Does this repo accept docker with source builds? I can send PR if you do! Thanks!

**Comment by ufoym** [comment]
@achalshah20 Sure! We appreciate PR containing the script **generator** (not the dockerfile itself, as all dockerfiles in deepo are generated automaticly) for source builds.

**Comment by achalshah20** [comment]
I just sent a PR #41

**Comment by ufoym** [comment]
@achalshah20 You can modify https://github.com/ufoym/deepo/blob/master/generator/modules/tensorflow.py
Example: https://github.com/ufoym/deepo/blob/master/generator/modules/caffe2.py

**Comment by ufoym** [comment]
Feel free to reopen if it doesn't work.
