### ISSUE TITLE
Questions regarding features

### ISSUE THREAD

**Issue by switch527** [ufoym/deepo#43]
Hi, I had a question regarding the integration of a few features and plans for the future of this distribution. This Docker image has made my life soooo much easier, so thank you for that. I just had questions around if you ever plan to build in integration for Anaconda python or Jupyter lab? I was also wondering if you had a set release schedule for when you update the image with new Cuda distributions. Do you do that at certain intervals or just major releases, e.g. 8.0, 9.0 etc. Thanks again, Deepo has been a life saver.

Best,
Steve

**Comment by ufoym** [comment]
Thank you for choosing deepo. Generally, we plan to keep deepo stable and updated.  So
- JupyterLab will replace the classic Jupyter Notebook in `ufoym/deepo:*-jupyter` after JupyterLab reaches 1.0.
- Images with newer CUDA distribution will be available when most DL frameworks are ready for that CUDA version. Meanwhile, previous images with older CUDA will be kept if all DL frameworks are still working.

Feel free to contact us if you have any further suggestion on strategy for updating deepo:-)
