### ISSUE TITLE
deepo:py27 caffe

### ISSUE THREAD

**Issue by mengzhibin** [ufoym/deepo#45]
when using python2.7 version deepo, I import caffe, and there is not Net and __version__ module, is there any problem about this version?
Looking forward for your reply.
@ufoym

**Comment by ufoym** [comment]
We've just tested `deepo:caffe-py27` with the following script
```
from caffe import Net
```
It works fine. Could you pls provide your test script? Thank you!

**Comment by ufoym** [comment]
Feel free to reopen this issue if the problem has not been resolved.

**Comment by mengzhibin** [comment]
I have use your ufoym/deepo:py27, and just try: from caffe import Net, but there is error: cannot import name Net

>>> from caffe import Net
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Net

e9d764a819d1        ufoym/deepo:py27    "bash" 

Thank you for your reply

**Comment by ufoym** [comment]
You should pull ```ufoym/deepo:all-py27``` instead.
Sorry for any inconvenience.

**Comment by tfriedel** [comment]
doesn't work even with  ufoym/deepo:all-py27

**Comment by ufoym** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/2270240/46679115-d9ca5f00-cc18-11e8-8173-ad56fdf56d8f.png)
