### ISSUE TITLE
Spyder (or any other IDE) support

### ISSUE THREAD

**Issue by sophia-wright-blue** [ufoym/deepo#47]
Hello, 

 This docker image makes developing models so much easier! Is there any way to access the ML libraries installed with this docker image through an IDE such Spyder?

  The jupyter notebook access is nice, but being able to run code in Spyder would make debugging a little bit easier.

**Comment by ufoym** [comment]
Thanks for choosing deepo.
We are not familiar with Spyder.
You mean [connect Spyder to a remote kernel](https://www.reddit.com/r/Python/comments/4szegr/has_anyone_been_able_to_connect_spyder_to_a/)?

**Comment by lizhimins** [comment]
Spyder is a simple integrated development environment developed by the author of Python (x, y). Compared with other Python development environments, its biggest advantage is that it mimics the "workspace" function of MATLAB, which makes it easy to observe and modify array values.
