### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by switch527** [ufoym/deepo#49]
I keep having some random dependency issues when using Deepo. Is there any plans (or could there be) to move over to the Ananconda python distributions from Continuum analytics? I've never had dependency issues with their package management system.

**Comment by ufoym** [comment]
Sorry for any inconvenience. 

Previously, we failed building all-in-one images based on Anaconda. 
And now we have no plan to add Anaconda back.
We appreciate related contributions.

BTW, could you provide more details about the `random dependency issues`?
Thank you!

**Comment by ufoym** [comment]
Feel free to reopen this issue if you have any further suggestion.
