### ISSUE TITLE
OpenCV function not implemented

### ISSUE THREAD

**Issue by syahrulhamdani** [ufoym/deepo#50]
I got unspecified error when trying to run opencv following this basic OpenCV [getting started](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_image_display/py_image_display.html#display-image). The error is:
```
OpenCV(3.4.1) Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /root/opencv/modules/highgui/src/window.cpp, line 636
Traceback (most recent call last):
  File "image_get_started.py", line 8, in <module>
    cv2.imshow("image", img)
cv2.error: OpenCV(3.4.1) /root/opencv/modules/highgui/src/window.cpp:636: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
```
I was using the `keras-cpu-py36` while adding OpenCV in its Dockerfile. Looking back to OpenCV and the `libgtk2.0-dev` and `pkg-config` wasn't yet included.

**Comment by ufoym** [comment]
It is not appropriate to use `imshow` in opencv without running X.
As an alternative, you can use functions like `imwrite` that do not require GUI support.
