### ISSUE TITLE
SomethingWrong with MxNet

### ISSUE THREAD

**Issue by Keneyr** [ufoym/deepo#53]
Wonderful deepo ! It made DL much more convenient. But I encountered some error while importing the framework MxNet.
I can import tensorflow, caffe, pytorch....But I can't import mxnet.
Python Interpreter told me : Illegal instruction(core dumped).
Have somebody else solved this problem before?

**Comment by ufoym** [comment]
Fixed. Feel free to reopen this issue and provide more details (e.g., which docker image) if you still have the same problem.
