### ISSUE TITLE
Support for package managers

### ISSUE THREAD

**Issue by kklemon** [ufoym/deepo#59]
The deepo generator already supports plenty of common libraries and packages for deep learning and data science but in many cases one has a need for additional libraries that are most probably not supported. After implementing some common NLP libraries for the generator by myself (see #56, #57, #58), I had to realize that writing mostly redundant code for each pip or apt package doesn't really makes sense at all. Instead I think it would be better to support common package managers and enable to add any of such packages dynamically.

My idea is that with this approach packages that are not explicitly implemented could be still be added as follows:
```bash
python generator.py Dockerfile keras pip+pandas pip+nltk==3.3 apt+ping
```
Of course this wouldn't work out for ones that are difficult to install like OpenCV but at least it would give users an easy way to add any not explicitly supported packages.

I already started working on an implementation but currently have to rethink everything again as the current design of the generator and composer would probably not allow to support such a feature.

**Comment by ufoym** [comment]
That's a great idea.

**Comment by ufoym** [comment]
How about parsing the input strings like `pip+pandas` `apt+ping` in
https://github.com/ufoym/deepo/blob/e384038ad6af08c30c10821d1f729121ee0b2d5c/generator/generate.py#L29-L34
then making a list of apt-modules & pip-modules and passing them into the `Composer`
https://github.com/ufoym/deepo/blob/e384038ad6af08c30c10821d1f729121ee0b2d5c/generator/generate.py#L35
and finally generating the corresponding scripts here:
https://github.com/ufoym/deepo/blob/e384038ad6af08c30c10821d1f729121ee0b2d5c/generator/core/composer.py#L61

**Comment by kklemon** [comment]
This was also my initial idea and I also made a rough implementation for this. In that there is a `PackageManager` base class which can be inherited to realize specific package managers. Each such implementation, for example an `PipPackageManager` class would take a package name as argument and then produce the corresponding install statement in its `build()` method. The only problem I encountered is that `Composer` is designed to work on base of module/classes and not their instances. This leads to the situation that you can't pass different instances of a single module (e.g. different instances of a `PackageManager`, each for a single pip package) to the composer. I don't know how to solve this properly at the moment except to redesign the code base to let the `Composer` take instances of modules.

Another approach I wanted to try is that each package manager module collects the packages to be installed in a class attribute before the composer is invoked. The composer does then instantiate each module as it is done currently and each package manager would then just build a single install statement with all packages that have been registered before.

If it is not completely clear what I mean, I could provide a basic implementation in the following days.
