### ISSUE TITLE
Boost 1.65 requires Cmake 3.9.3 or newer

### ISSUE THREAD

**Issue by mvpel** [ufoym/deepo#63]
Ubuntu 16.04 supplies Cmake 3.5.1-1ubuntu3, but Boost 1.65.1, installed in the Deepo containers, requires 3.9.3 or newer:

https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version 

CMake cannot detect the dependencies between the different Boost libraries. They have explicitly implemented in FindBoost.

For every Boost release this information is added by the CMake maintainers and it gets part of the next CMake release. So you have to make sure, that your CMake version was released after the Boost version you try to find.

Boost 1.63 requires CMake 3.7 or newer.
Boost 1.64 requires CMake 3.8 or newer.
Boost 1.65 and 1.65.1 require CMake 3.9.3 or newer.
Boost 1.66 requires CMake 3.11 or newer.
Boost 1.67 requires CMake 3.12 or newer.
Boost 1.68 and 1.69 require CMake 3.13 or newer.

**Comment by ufoym** [comment]
In deepo, module `Boost` depends on module `Tool`, which contain scripts for upgrading `CMake`.

**Comment by ufoym** [comment]
Feel free to reopen this issue if the problem persists.
