### ISSUE TITLE
Request to add torchvision

### ISSUE THREAD

**Issue by cuihaoleo** [ufoym/deepo#64]
Pytorch users need [torchvision](https://github.com/pytorch/vision).

Thanks!

**Comment by ufoym** [comment]
Sorry for mistakenly deleting `torchvision` in commit 0c302ed755166483e78670608c675cd65f8321b9.
![image](https://user-images.githubusercontent.com/2270240/48428142-5070f400-e7a5-11e8-9bf3-ceb58350764e.png)
