### ISSUE TITLE
pytorch stable version 1.0.0

### ISSUE THREAD

**Issue by kbc8894** [ufoym/deepo#70]
Hi, @ufoym 
First of all, I appreciate your repo.
and then, 
I find that currently deepo use a nightly build version on pytorch.
and I check your commit log.
You changed 0.4.1 version to nightly version at 0c302ed755166483e78670608c675cd65f8321b9.
I think that you can restore with version 1.0.0

PS: If you want, I can make pull request.

**Comment by ufoym** [comment]
We install the latest modules by default. You can, of course, specify the version you like and build your own images.
