### ISSUE TITLE
why there is a program named ethminer in the container created with the images?

### ISSUE THREAD

**Issue by xml94** [ufoym/deepo#73]
I used two of the versions of these images, and then created containers.
But, once I don't use my GPUs, then a program appeared and uses automatically GPUs.

**Comment by ufoym** [comment]
Which images?

**Comment by ufoym** [comment]
All [official deepo images](https://hub.docker.com/r/ufoym/deepo) are automatically built on  [CircleCI](https://circleci.com/gh/ufoym/workflows/deepo) using [these Dockerfiles](https://github.com/ufoym/deepo/tree/master/docker).

**Comment by xml94** [comment]
1. I used two of images, both of them had same questions. The first image is ufoym/deepo:all-jupyter-py36-cu90, and the second is ufoym/deepo:all-jupyter-py27.

2. I used this command: docker pull ufoym/deepo:all-jupyter-py36-cu90 to download the images.

3. this command is used to generate a container from images: nvidia-docker run --name xxx  --restart=always -it -p 8888:8888 -v xxx:/home ufoym/deepo:all-py36-jupyter jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/home'

4. the program .ethminer appeared after several hours of creating a container and don't use the GPUs and don't kill the container.

**Comment by ufoym** [comment]
We have been testing `ufoym/deepo:all-jupyter-py36-cu90` for 4+ hours. But we still can't find any program called `ethminer` (by using `top`, `nvidia-smi`, and `find / -name ethminer`). Is it convenient for you to test it in another machine?

**Comment by xml94** [comment]
> We have been testing `ufoym/deepo:all-jupyter-py36-cu90` for 4+ hours. But we still can't find any program called `ethminer` (by using `top`, `nvidia-smi`, and `find / -name ethminer`). Is it convenient for you to test it in another machine?

1. In my case, I can find the program after longer than 4 hours., maybe 10 hours.
2. I use this command to see what has happened: watch -n 0.1 nvidia-smi.
3. In the day evening before yesterday, I tested a situation. I generated a new container with a image, and then executed a jupyter code and latter the GPUs are available. Yesterday morning, I saw the program named .ethminer.  Finally, I stoped the container and remove the container, the program disappeared.

I save two pictures in this situation:
![_20181227212258](https://user-images.githubusercontent.com/30434881/50624975-37e0b700-0f68-11e9-9264-c3da5e80b6d7.png)
![_20190102084541](https://user-images.githubusercontent.com/30434881/50624976-37e0b700-0f68-11e9-9193-f4ea673b0bc5.png)

**Comment by ufoym** [comment]
Thank you for your feedback.
Could you locate the program and find out when / how the process started?
BTW, ensure that no one (except you) can access your notebook especially when you start the container by `nvidia-docker run --name xxx --restart=always -it -p 8888:8888 -v xxx:/home ufoym/deepo:all-py36-jupyter jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/home'`. As one can install / run any program on your container via a remote browser.

**Comment by xml94** [comment]
I see.
I will chek further steps.
Thanks very much.

**Comment by ufoym** [comment]
You're welcome. Feel free to reopen this issue if the problem persists.
