### ISSUE TITLE
errors with caffe2

### ISSUE THREAD

**Issue by beatthat** [ufoym/deepo#74]
Thanks for creating and sharing this needed tool!

I'm trying to use a deepo:caffe2-py36-cu90 docker image as a basis for running Detectron with python3.6 (AFAIKT all shared Detectron docker images are bases on fb's caffe docker images, which are all py2.7)

I'm able to build the docker image but it throws caffe2 errors when I run Detectron.

Without getting too much in the weeds with the Detectron code, I get the following basic error with deepo caffe2-py36-cu90:

STEPS:
```bash
docker run --runtime=nvidia --rm -it ufoym/deepo:caffe2-py36-cu90 bash -c "python -c 'from caffe2.python import workspace;print(1)'"
```

EXPECTED
- should print '1'

OBSERVED:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'caffe2'
```

NOTE:

The same command works as expected with the official caffe docker image, e.g.

```bash
docker run --runtime=nvidia --rm -it caffe2/caffe2:snapshot-py2-cuda9.0-cudnn7-ubuntu16.04 bash -c "python -c 'from caffe2.python import workspace;print(1)'"
# prints '1'
```

**Comment by ufoym** [comment]
Fixed. And now`caffe2` has been merged to the `pytorch` image. Try 
```
docker run --runtime=nvidia --rm -it ufoym/deepo:pytorch bash -c "python -c 'from caffe2.python import workspace;print(1)'"
```

**Comment by beatthat** [comment]
Thanks! The image I'm trying to use `ufoym/deepo:caffe2-py36-cu90` is not updated in docker hub. 

Are you able to push the updated image?
