### ISSUE TITLE
opencv error: BVIDIOC_REQBUFS: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by sanzgiri** [ufoym/deepo#76]
I get this error `BVIDIOC_REQBUFS: Inappropriate ioctl for device` while opening an mp4 file from a docker image built using this dockerfile.

```
import numpy as np
import cv2
cap = cv2.VideoCapture(videoFile)

print(cap.isOpened()) # False
print(cap.read()) 
```
Returns
```
False
(False, None)
```
I am unable to open an mp4 file in my container because of this.  Appreciate any help.

Thanks,
Ashutosh

**Comment by achillesrasquinha** [comment]
Hmm! This doesn't solve the issue but I've considered using `scikit-video` instead.

```python
>> import skvideo.io
>>> reader = skvideo.io.vreader('foobar.mp4')
>>> for frame in reader:
		print(frame.shape)
```

Works flawlessly within deepo!

To install within an existent container simply,

```
$ docker exec DEEPO_CONTAINER_NAME "apt-get update && apt-get install -y ffmpeg && pip install scikit-video"

**Comment by sanzgiri** [comment]
@achillesrasquinha - I was able to get the opencv functionality I need by adding the following packages via pip:
`opencv-python-headless opencv-contrib-python-headless`
