### ISSUE TITLE
Using deepo remotely from macOS

### ISSUE THREAD

**Issue by paulcbetts** [ufoym/deepo#8]
This is more of a general question, if you don't know off the top of your head please feel free to close. Is there any way to use deepo / nvidia-docker with a macOS machine running Docker client commands remotely connecting to a Linux `docker-machine` with nvidia-docker configured?

**Comment by thefiddler** [comment]
You can connect to the remote machine via ssh and spin up deepo there. Does that cover your use-case?

**Comment by paulcbetts** [comment]
@thefiddler Yeah, it's a bummer but it probably works. Thanks for the idea.
