### ISSUE TITLE
Not able to install packages using apt-get

### ISSUE THREAD

**Issue by codeslord** [ufoym/deepo#82]
I am getting the following error while trying to install packages using apt in container created using image ufoym/deepo:all-py36-jupyter-cpu.

Command given:

apt-get install ffmpeg

The following NEW packages will be installed:
  ffmpeg i965-va-driver libaacs0 libasound2 libasound2-data libass5 libasyncns0 libavc1394-0 libavcodec-ffmpeg56 libavdevice-ffmpeg56 libavfilter-ffmpeg5
  libavformat-ffmpeg56 libavresample-ffmpeg2 libavutil-ffmpeg54 libbdplus0 libbluray1 libbs2b0 libbsd0 libcaca0 libcdio-cdda1 libcdio-paranoia1 libcdio13
  libcrystalhd3 libdc1394-22 libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2 libelf1 libflac8 libflite1 libfribidi0
  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgme0 libgsm1 libiec61883-0 libjack-jackd2-0 libjson-c2 libllvm6.0 libmodplug1 libmp3lame0 libogg0 libopenal-data
  libopenal1 libopencv-core2.4v5 libopencv-imgproc2.4v5 libopenjpeg5 libopus0 liborc-0.4-0 libpciaccess0 libpostproc-ffmpeg53 libpulse0 libraw1394-11 libsamplerate0
  libschroedinger-1.0-0 libsdl1.2debian libsensors4 libshine3 libslang2 libsndfile1 libsodium18 libsoxr0 libspeex1 libssh-gcrypt-4 libswresample-ffmpeg1
  libswscale-ffmpeg3 libtbb2 libtheora0 libtwolame0 libtxc-dxtn-s2tc0 libusb-1.0-0 libva1 libvdpau1 libvorbis0a libvorbisenc2 libwavpack1 libwebp5 libwrap0
  libx11-xcb1 libx264-148 libx265-79 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shape0 libxcb-sync1 libxcb-xfixes0 libxdamage1 libxfixes3
  libxshmfence1 libxv1 libxvidcore4 libxxf86vm1 libzmq5 libzvbi-common libzvbi0 mesa-va-drivers mesa-vdpau-drivers tcpd va-driver-all vdpau-driver-all
0 upgraded, 107 newly installed, 0 to remove and 111 not upgraded.
Need to get 54.9 MB of archives.
After this operation, 337 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libjson-c2 amd64 0.11-4ubuntu2
  403  Forbidden [IP: 91.189.88.149 80]
Err:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 libasyncns0 amd64 0.8-5build1
  Error reading from server. Remote end closed connection [IP: 91.189.88.149 80]
Err:3 http://archive.ubuntu.com/ubuntu xenial/universe amd64 libcrystalhd3 amd64 1:0.0~git20110715.fdd2f19-11build1
  403  Forbidden [IP: 91.189.88.149 80]

I am running docker for windows.
Could you please help me understand and mitigate the issue?

**Comment by ufoym** [comment]
See https://serverfault.com/questions/816900/ubuntu-apt-get-update-403-forbidden-in-docker-on-azure-vm
