### ISSUE TITLE
python generate.py Dockerfile tensorflow  giving error 

### ISSUE THREAD

**Issue by deo999** [ufoym/deepo#83]
Traceback (most recent call last):
  File "generate.py", line 42, in <module>
    main()
  File "generate.py", line 38, in main
    f.write(composer.to_dockerfile())
  File "/home/deepo/deepo/generator/core/composer.py", line 59, in to_dockerfile
    ]) for m in self.instances
  File "/home/deepo/deepo/generator/modules/python.py", line 17, in build
    if self.composer.ubuntu_ver.startswith("18."):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by deo999** [comment]
why you have cloased this can you please tell solution.

**Comment by ufoym** [comment]
We make sure that `self.composer.ubuntu_ver` never be `None`. See https://github.com/ufoym/deepo/blob/654e8777e6a014a565ce3969c8f68ee2f9881944/generator/generate.py#L25

**Comment by deo999** [comment]
ok now that working but have one doubt, whe we going to run this command:
 python generate.py Dockerfile tensorflow
This should generate a Dockerfilefor tensorflow, my doubt is this for cpu or nvidia-gpu, how to modify to create dockerfile for gpu.

**Comment by ufoym** [comment]
CPU:
```
python generate.py Dockerfile tensorflow
```

CUDA 9.0 / CuDNN 7:
```
python generate.py Dockerfile tensorflow --cuda-ver 9.0 --cudnn-ver 7
```
See https://github.com/ufoym/deepo/blob/master/scripts/gen-docker.sh for more examples.
