### ISSUE TITLE
 docker-ce and docker  has  diff usage

### ISSUE THREAD

**Issue by haohaiwei** [ufoym/deepo#84]
for docker-ce use command 'docker run --runtime=nvidia -it ufoym/deepo bash'
for docker use command 'docker run -it ufoym/deepo bash'

**Comment by haohaiwei** [comment]
for docker-ce use command 'docker run --runtime=nvidia -it ufoym/deepo bash'
for docker use command 'docker run  -it ufoym/deepo bash'

**Comment by ufoym** [comment]
Is there any official reference showing the difference of usage?

**Comment by ufoym** [comment]
Feel free to reopen this issue if there is.
