### ISSUE TITLE
Nonexistent nvidia/cuda image referenced

### ISSUE THREAD

**Issue by ipa-oro** [ufoym/deepo#85]
Hi,
I think you broke all cuda based images with commit f441d17124a90626655561c5349c66f3333129ca by referencing the nonexistent base image nvidia/cuda:9.0-cudnn7-devel-ubuntu18.04

I believe only CUDA 9.2 and CUDA 10.0 images support Ubuntu 18.04.

Regards,

**Comment by ufoym** [comment]
Sorry, my fault. We'll fix it right now. Thanks pretty much!
