### ISSUE TITLE
how to create docker file for conda based python package

### ISSUE THREAD

**Issue by deo999** [ufoym/deepo#87]
i want to add some python based library into it using conda can you please tell how to  do that  for both pip  install <name of package> and conda install <name of python package>

**Comment by ufoym** [comment]
`conda`, as an unessential non-DL library, is too heavy for `deepo`.
However, you can follow [the installation instructions](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) to install `conda` in your own containers / images.

**Comment by deo999** [comment]
ok tell me one thing if i want  to add other  python packages then how to create docker file for that with pip

**Comment by ufoym** [comment]
@deo999 

Dockerfile:
···
FROM ufoym/deepo
RUN pip install XXX
···
