### ISSUE TITLE
Can deepo share data between my host machine and the container?

### ISSUE THREAD

**Issue by lk1983823** [ufoym/deepo#89]
Can deepo share data between my host machine and the container? I want the container to read data from a shareholder in the host and receive model ouput from the container. I know that dl-docker can do this. Thank you.

**Comment by ufoym** [comment]
If you want to share your data and configurations between the host (your machine or VM) and the container in which you are using Deepo, use the `-v` option, e.g.
```
docker run -it -v /host/data:/data -v /host/config:/config ufoym/deepo:cpu bash
```
This will make `/host/data` from the host visible as `/data` in the container, and `/host/config` as `/config`.

**Comment by lk1983823** [comment]
Thanks a lot 

发自我的 iPhone
