### ISSUE TITLE
how to  create dockerfile for cuada gpu not cpu

### ISSUE THREAD

**Issue by deo999** [ufoym/deepo#96]
hey  i am getting dockerfile for cpu for any require python library but how to use it for cuda docker image please tell
python generate.py Dockerfile pytorch lasagne

**Comment by ufoym** [comment]
```
python ../generator/generate.py ../docker/Dockerfile pytorch lasagne python==3.6 --cuda-ver 10.0 --cudnn-ver 7
```

see https://github.com/ufoym/deepo/blob/master/scripts/gen-docker.sh for more examples.
