### ISSUE TITLE
How to specify the version of CUDA to CUDA 10?

### ISSUE THREAD

**Issue by 356255531** [ufoym/deepo#99]
Hi, community,
I am new to Docker and wonder how could we explicitly specify the version of CUDA to 10. 
It is important since CUDA 9 will somehow  damage our GPUs (RTX 2080) permanently. Yes, it broke already three of them.
I see deepo already supports CUDA10 and can we just follow the instruction at the master branch? How could we work with those Tags (CUDA 10 / Python 3.6)? 
LG
Zhiwei

**Comment by ufoym** [comment]
By default, the CUDA version of the latest images is now 10.0.

e.g.,
```
docker pull ufoym/deepo
```
you get the all-in-one image with CUDA 10.0.
